# Marp Configuration
allowLocalFiles: true
html: true
engine: '@marp-team/marp-core'
themeSet: './themes'
template: bespoke
options:
  looseYAML: true
  markdown:
    breaks: true
    html: true
theme: default
